# Generated by Django 3.2 on 2025-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('afp', models.CharField(blank=True, max_length=100, null=True)),
                ('compensation_fund', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('socioeconomic_stratum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
