# Generated by Django 3.2 on 2025-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Abierta', max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_execution',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Crítico', 'Crítico')], max_length=20)),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('seguimiento', 'En seguimiento')], default='abierto', max_length=20)),
                ('closing_evidence', models.FileField(blank=True, null=True, upload_to='audit_findings_closing/')),
            ],
            options={
                'db_table': 'audit_finding',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=300)),
                ('expected_result', models.CharField(blank=True, max_length=300)),
                ('evidence_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'audit_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('parcial', 'Cumple parcialmente')], max_length=30)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='audit_evidence/')),
                ('observation', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_result',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('affected_table', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
