# Generated by Django 3.2 on 2025-08-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemaudit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
    ]
