# Generated by Django 3.2 on 2025-08-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0002_systemaudit_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
        ('acciones_correctivas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auditresult_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_auditresult_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='auditoria.auditexecution'),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.audititem'),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auditresult_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audititem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auditoria.auditchecklist'),
        ),
        migrations.AddField(
            model_name='audititem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audititem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audititem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_audititem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audititem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audititem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='action_item',
            field=models.ForeignKey(blank=True, help_text='Acción correctiva asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acciones_correctivas.actionitem'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auditfinding_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_auditfinding_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='auditoria.auditexecution'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auditfinding_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditchecklist'),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auditexecution_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_auditexecution_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auditexecution_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auditchecklist_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_auditchecklist_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auditchecklist_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
